sudo: required

language: java

services:
  - docker

jdk:
  - oraclejdk8
  - openjdk8

cache:
  directories:
    - .autoconf
env:
  matrix:
    - TEST_SET="-Ptravis_main"
    - TEST_SET="-fn -Dtest=BroadcasterTest,ClientCloseTest,ResponseWriterOutputStreamTest -DfailIfNoTests=false"

install: true

script:
  - bash travis.sh $TEST_SET